[build]
  command = "yarn build"
  publish = "dist"

[template.environment]
  VUE_APP_CT_PROJECT_KEY = "Your commercetools project key (optional)"
  VUE_APP_CT_CLIENT_ID = "Your commercetools client ID (optional)"
  VUE_APP_CT_CLIENT_SECRET = "Your commercetools client secret (optional)"
  VUE_APP_CT_AUTH_HOST = "Auth host (optional, default https://auth.commercetools.com)"
  VUE_APP_CT_API_HOST = "API host (optional, default https://api.commercetools.com)"
