# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
        environment:
          # this enables colors in the output
          TERM: xterm

    working_directory: ~/sunrise-spa

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          key: v1-deps-{{ .Branch }}
          key: v1-deps

      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          paths:
            # cache both yarn and Cypress
            - ~/.cache
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: Run E2E tests
          command: yarn test:e2e

      - store_test_results:
          path: e2e-results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
